apiVersion: v1
kind: Service
metadata:
  name: app-nodejs
  labels:
    app: app-nodejs
spec:
  type: LoadBalancer
  selector:
    app: app-nodejs
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001