- name: Application Deployment management role
  tags: [web_app]
  block:
    - name: Wiper tasks
      when: web_app_full_wipe is defined and web_app_full_wipe
      ansible.builtin.import_tasks:
        wipe.yml

    - name: Complete "Configure and run" tasks
      ansible.builtin.import_tasks:
        configure.yml