- name: Install aptitude
  ansible.builtin.apt:
    name: aptitude
    state: present
    update_cache: true

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - curl
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: present
    update_cache: true

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    name: docker-ce
    state: present
    update_cache: true