name: Python CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/app_python/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Dependencies
      run: |
        cd app_python
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Linter
      run: |
        cd app_python
        pip install flake8
        flake8 .
    
    - name: Tests
      run: |
        python -m unittest discover -s app_python/tests
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image for Python
      run: |
        cd app_python
        docker build -t flask-moscow-time-app:latest .

    - name: Push Docker image for Python
      run: |
        docker tag flask-moscow-time-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/flask-moscow-time-app:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-moscow-time-app:latest

    - name: Build Docker image for NodeJS
      run: |
        cd app_nodejs
        docker build -t node-world-clock-app:latest .

    - name: Push Docker image for NodeJS
      run: |
        docker tag node-world-clock-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/node-world-clock-app:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-world-clock-app:latest

  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/app_python/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Dependencies
      run: |
        cd app_python
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Copy requirements.txt
      run: |
        cp app_python/requirements.txt requirements.txt
    
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python-3.8@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}